
Write-White "Level 0"
. "$((Get-Item $PSScriptRoot))\scripts\common\start-execution.ps1"
Write-White "Level 1"
. "$((Get-Item $PSScriptRoot))\scripts\common\start-execution.ps1"
Write-White "Level 2"
. "$((Get-Item $PSScriptRoot))\scripts\common\start-execution.ps1"
Write-White "Level 3"

. "$((Get-Item $PSScriptRoot))\scripts\common\end-execution.ps1"
Write-White "Level 2"
. "$((Get-Item $PSScriptRoot))\scripts\common\end-execution.ps1"
Write-White "Level 1"
. "$((Get-Item $PSScriptRoot))\scripts\common\end-execution.ps1"
Write-White "Level 0"
